# Generated by Django 3.0.8 on 2020-09-09 10:17

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('unique_id', models.CharField(default=users.models.random_code, max_length=10)),
                ('status', models.CharField(choices=[('candidate', 'candidate'), ('examiner', 'examiner')], default=False, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExaminerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mister'), ('Mrs', 'Mistress'), ('Dr', 'Doctor'), ('Prof', 'Professor'), ('Engr', 'Engineer'), ('Chief', 'Chief')], max_length=10, null=True)),
                ('middle_name', models.CharField(help_text='Enter your middle name here if any', max_length=25, null=True)),
                ('qualification', models.CharField(choices=[('NCE', 'NCE'), ('HND', 'HND'), ('B.Sc', 'B.Sc'), ('M.Sc', 'M.Sc'), ('PhD', 'PhD')], max_length=8, null=True)),
                ('document', models.FileField(null=True, upload_to='documents/%Y/%m/%d/')),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_pics/%Y/%m/%d/')),
                ('discipline', models.CharField(max_length=200, null=True)),
                ('published_work', models.URLField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(help_text='Format: YYYY-MM-DD', null=True)),
                ('age', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('religion', models.CharField(choices=[('Christian', 'Christianity'), ('Muslim', 'Islam')], max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('about_me', models.TextField(help_text='Write something about yourself, not more than 300 words', max_length=300, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('examiner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(help_text='Enter your middle name here if any', max_length=25, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(help_text='Format: YYYY-MM-DD', null=True)),
                ('age', models.BigIntegerField(null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('religion', models.CharField(choices=[('Christian', 'Christianity'), ('Muslim', 'Islam')], max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('hobbies', models.CharField(max_length=200, null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_pics/%Y/%m/%d/')),
                ('about_me', models.TextField(help_text='Write something about yourself, not more than 300 words', max_length=300, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
