# Generated by Django 3.0.8 on 2020-09-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclass',
            old_name='examiner',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='studentlevel',
            old_name='examiner',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='examiner',
            new_name='admin',
        ),
    ]
