# Generated by Django 3.0.8 on 2020-09-10 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0002_auto_20200909_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Select the department you belong to', on_delete=django.db.models.deletion.CASCADE, to='exams.Department')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.StudentClass')),
                ('student_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.StudentLevel')),
                ('subject_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_1', to='exams.Subjects')),
                ('subject_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_2', to='exams.Subjects')),
                ('subject_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_3', to='exams.Subjects')),
                ('subject_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_4', to='exams.Subjects')),
                ('subject_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_5', to='exams.Subjects')),
                ('subject_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_6', to='exams.Subjects')),
                ('subject_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_7', to='exams.Subjects')),
                ('subject_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_8', to='exams.Subjects')),
                ('subject_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_9', to='exams.Subjects')),
            ],
        ),
    ]
