# Generated by Django 3.0.8 on 2020-09-11 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examregistration',
            name='subject_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_1', to='exams.Subjects'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='subject_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_2', to='exams.Subjects'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='subject_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_3', to='exams.Subjects'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='subject_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_4', to='exams.Subjects'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='subject_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_5', to='exams.Subjects'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='subject_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_6', to='exams.Subjects'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='subject_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_7', to='exams.Subjects'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='subject_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_8', to='exams.Subjects'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='subject_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_9', to='exams.Subjects'),
        ),
    ]
